name: Time DevOps Project Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/time-devops-project:${{ env.SHORT_SHA }} .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/time-devops-project:${{ env.SHORT_SHA }}
      
      - name: Configure Git Author
        run: |
          git config --local user.name "marck-devops"
          git config --local user.email "marck.devops@gmail.com"

      - name: Update Helm Chart with new Image
        run: |
          sed -i "s/tag:.*/tag: ${{ env.SHORT_SHA }}/" time-devops-project/values.yaml
          git add ./time-devops-project/values.yaml
          git commit -m "Update Helm Chart with new Image"
          git push